[project]
name = "returntrend-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "feedparser>=6.0.11",
    "langchain-ollama>=0.3.6",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.3",
]
